load(":defs.bzl", "complete_release", "first_party_release")

oncall("hctl2")

export_file(
    name = "export-first-party.sh",
    src = "export-first-party.sh",
)

export_file(
    name = "license",
    src = "assets/LICENSE",
    visibility = ["PUBLIC"],
)

export_file(
    name = "usage",
    src = "assets/USAGE.md",
    visibility = ["PUBLIC"],
)

first_party_release(name = "first-party")

complete_release(name = "complete")
