load("//build/rules:ci.bzl", "CI_FAST")
load("//build/rules:rust.bzl", "HCTL2_RUST_EDITION", "HCTL2_RUSTC_FLAGS", "hctl2_cargo_env")

oncall("hctl2")

rust_library(
    name = "hctl2_tool",
    srcs = ["src/lib.rs"],
    crate_root = "src/lib.rs",
    deps = [
        "root//crates/hctl2-facts:hctl2_facts",
        "root//third-party/rust:clap",
        "root//third-party/rust:serde_json",
    ],
    edition = HCTL2_RUST_EDITION,
    env = hctl2_cargo_env(),
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    tests = [":unit_test"],
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "hctl2-tool",
    srcs = ["src/main.rs"],
    crate_root = "src/main.rs",
    deps = [":hctl2_tool"],
    edition = HCTL2_RUST_EDITION,
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    tests = [":smoke_test"],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "unit_test",
    srcs = ["src/lib.rs"],
    crate_root = "src/lib.rs",
    deps = [
        "root//crates/hctl2-facts:hctl2_facts",
        "root//third-party/rust:clap",
        "root//third-party/rust:serde_json",
    ],
    edition = HCTL2_RUST_EDITION,
    env = hctl2_cargo_env(),
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    visibility = ["PUBLIC"],
)

rust_test(
    name = "smoke_test",
    srcs = ["tests/smoke.rs"],
    crate_root = "tests/smoke.rs",
    deps = ["root//third-party/rust:serde_json"],
    edition = HCTL2_RUST_EDITION,
    env = hctl2_cargo_env() | {
        "CARGO_BIN_EXE_hctl2-tool": "$(location :hctl2-tool)",
    },
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "clippy",
    srcs = {
        "binary": ":hctl2-tool[clippy.txt]",
        "library": ":hctl2_tool[clippy.txt]",
        "smoke": ":smoke_test[clippy.txt]",
        "unit": ":unit_test[clippy.txt]",
    },
    labels = CI_FAST,
    visibility = ["PUBLIC"],
)
