load("//build/rules:ci.bzl", "CI_FAST")
load("//build/rules:rust.bzl", "HCTL2_RUST_EDITION", "HCTL2_RUSTC_FLAGS", "hctl2_cargo_env")
oncall("hctl2")
filegroup(name = "docs", srcs = glob(["**/*.md"]), visibility = ["PUBLIC"])
rust_library(name = "context", srcs = ["src/lib.rs"], crate_root = "src/lib.rs", deps = ["root//crates/agency-proto:agency_proto"],
    edition = HCTL2_RUST_EDITION, rustc_flags = HCTL2_RUSTC_FLAGS, env = hctl2_cargo_env(), labels = CI_FAST, visibility = ["PUBLIC"])
filegroup(name = "clippy", srcs = {"library": ":context[clippy.txt]"}, labels = CI_FAST, visibility = ["PUBLIC"])
