load(":defs.bzl", "declare_external_dependencies")

oncall("hctl2")

declare_external_dependencies(
    build_sources = {
        source: source
        for source in glob([
            "cinny-config.json",
            "common/action.sh",
            "common/build.sh",
            "platforms/linux/bootstrap.sh",
            "platforms/macos/bootstrap.sh",
            "platforms/macos/common.sh",
            "platforms/macos/tuwunel-prebuilt.sh",
            "platforms/macos/tuwunel.sh",
        ])
    },
    package_sources = {
        source: source
        for source in glob([
            "PACKAGE-README.md",
            "SOURCE-INFO.md.in",
            "SOURCE-PACKAGE-README.md.in",
            "common/action.sh",
            "common/build.sh",
            "common/package.sh",
            "common/runtime.sh",
            "hctl2-services",
            "install-package.sh",
            "platforms/linux/bootstrap.sh",
            "platforms/linux/package.sh",
            "platforms/linux/runtime.sh",
            "platforms/macos/bootstrap.sh",
            "platforms/macos/common.sh",
            "platforms/macos/package.sh",
            "platforms/macos/runtime.sh",
            "smoke.sh",
            "start.sh",
            "status.sh",
            "stop.sh",
        ])
    },
    test_sources = {
        source: source
        for source in glob([
            "common/action.sh",
            "common/build.sh",
            "common/test-package.sh",
        ])
    },
)
