load(":defs.bzl", "declare_external_dependencies")

oncall("hctl2")

declare_external_dependencies(
    build_sources = {
        source: source
        for source in glob([
            "bootstrap-linux-x86_64.sh",
            "bootstrap-macos-aarch64.sh",
            "bootstrap-macos-x86_64.sh",
            "cinny-config.json",
            "common/build.sh",
            "common/versions.sh",
            "platforms/linux/bootstrap.sh",
            "platforms/macos/bootstrap.sh",
            "platforms/macos/versions.sh",
            "targets/linux-x86_64.sh",
            "targets/macos-aarch64.sh",
            "targets/macos-x86_64.sh",
        ])
    },
)
