load("//build/rules:ci.bzl", "CI_FAST")
load("//build/rules:rust.bzl", "HCTL2_RUST_EDITION", "HCTL2_RUSTC_FLAGS", "hctl2_cargo_env")

oncall("hctl2")

FOUNDATION_DEPS = [
    "root//third-party/rust:keyring",
    "root//third-party/rust:rusqlite",
    "root//third-party/rust:serde_json",
    "root//third-party/rust:serde_json_canonicalizer",
    "root//third-party/rust:sha2",
]

rust_library(
    name = "hctl2_foundation",
    srcs = ["src/lib.rs"],
    crate_root = "src/lib.rs",
    deps = FOUNDATION_DEPS,
    edition = HCTL2_RUST_EDITION,
    env = hctl2_cargo_env(),
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    tests = [":unit_test"],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "unit_test",
    srcs = glob([
        "src/lib.rs",
        "testdata/**",
    ]),
    crate_root = "src/lib.rs",
    deps = FOUNDATION_DEPS,
    edition = HCTL2_RUST_EDITION,
    env = hctl2_cargo_env(),
    labels = CI_FAST,
    rustc_flags = HCTL2_RUSTC_FLAGS,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "clippy",
    srcs = {
        "library": ":hctl2_foundation[clippy.txt]",
        "unit": ":unit_test[clippy.txt]",
    },
    labels = CI_FAST,
    visibility = ["PUBLIC"],
)
