//! Generated control contract. Sources come from the Buck proto genrule.

// Everything below the include! is generated by the Buck genrule, not written
// here, so lints report on code no one edits. Listing the lints individually
// leaves the gate at the mercy of whatever the generator emits next; widening
// to clippy::all would also cover hand-written code added to this file later.
#![allow(
    clippy::doc_markdown,
    clippy::must_use_candidate,
    clippy::pedantic,
    clippy::useless_borrows_in_formatting
)]

include!(concat!(env!("HCTL2_PROTO_OUT"), "/mod.rs"));
