load("//build/rules:ci.bzl", "CI_FULL")

oncall("hctl2")

export_file(
    name = "Cargo.toml",
    src = "Cargo.toml",
    visibility = ["PUBLIC"],
)

filegroup(
    name = "clippy",
    srcs = {
        "hctl2-protocol": "root//crates/hctl2-protocol:clippy",
        "hctl2-tool": "root//apps/hctl2-tool:clippy",
    },
    labels = CI_FULL,
    visibility = ["PUBLIC"],
)
